# build docker image and push to docker hub
name: ci

on:
  push:
    branches:
    - "master"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: check out
      uses: actions/checkout@v3

    - name: Login to docker hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Set up Docker buildx
      uses: docker/setup-buildx-actions@v2

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-alpine:red-yellow